# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy the MCP server package.json from the unity-mcp-server subdirectory (monorepo structure)
COPY unity-mcp-server/package.json ./

# Install dependencies without running scripts (skip prepare scripts)
RUN npm install --ignore-scripts

# Copy the entire unity-mcp-server directory into the container
COPY unity-mcp-server/ ./

# Build the MCP server
RUN npm run build

# Set the CMD to start the MCP server
CMD [ "npm", "start" ]
